import { useState } from 'react'
import type { EssayReview } from '../../lib/committee-simulator.js'
import type { PmEssayReview } from '../../lib/schemas.js'

type Props = {
  reviews: PmEssayReview[]
}

function formatDimension(key: string): string {
  return key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
}

function ScoreBar({ score }: { score: number }) {
  const color = score >= 4 ? 'bg-green-500' : score === 3 ? 'bg-amber-500' : 'bg-red-500'
  return (
    <div className="w-full h-1.5 bg-gray-100 rounded-full overflow-hidden">
      <div className={`h-full ${color}`} style={{ width: `${(score / 5) * 100}%` }} />
    </div>
  )
}

/**
 * Read-only — every review is generated by the review-essay CLI, never from
 * this page. A live model call from the browser would require shipping
 * ANTHROPIC_API_KEY in the client bundle, so the review button intentionally
 * does not exist here (see docs/handoffs/2026-07-03-premed-session-8.md).
 */
export function EssayReviewSection({ reviews }: Props) {
  const [selectedId, setSelectedId] = useState<string | null>(reviews[0]?.id ?? null)
  const selected = reviews.find(r => r.id === selectedId) ?? reviews[0] ?? null
  const review = selected ? (selected.review as unknown as EssayReview) : null

  return (
    <section className="bg-white rounded-2xl border border-gray-200 p-6">
      <h2 className="text-lg font-semibold text-gray-900 mb-1">Committee Simulator</h2>
      <p className="text-xs text-gray-400 mb-4">Critique only — it names problems, it never rewrites your essay for you</p>

      <div className="bg-indigo-50 border border-indigo-100 rounded-xl p-3 mb-4 text-xs text-indigo-900">
        New reviews are generated from the command line (a live model call, so it can't be triggered from this page):
        <code className="block mt-1 bg-white rounded px-2 py-1 text-indigo-700 overflow-x-auto">
          npm run review-essay -- --user &lt;id&gt; --file draft.txt [--school "School Name"]
        </code>
      </div>

      {reviews.length === 0 && <p className="text-sm text-gray-400">No reviews yet — run the CLI above to generate your first one.</p>}

      {reviews.length > 0 && (
        <div className="flex gap-4">
          <div className="w-36 flex-shrink-0 space-y-1">
            {reviews.map(r => (
              <button
                key={r.id}
                onClick={() => setSelectedId(r.id)}
                className={`w-full text-left px-2 py-1.5 rounded-lg text-xs ${
                  (selectedId ?? reviews[0].id) === r.id ? 'bg-indigo-100 text-indigo-700 font-medium' : 'text-gray-500 hover:bg-gray-50'
                }`}
              >
                {new Date(r.created_at).toLocaleDateString()}
              </button>
            ))}
          </div>

          {review && (
            <div className="flex-1 space-y-4 min-w-0">
              <div className="space-y-3">
                {review.dimensionScores.map(d => (
                  <div key={d.dimension}>
                    <div className="flex items-center justify-between text-xs mb-0.5">
                      <span className="font-medium text-gray-800">{formatDimension(d.dimension)}</span>
                      <span className="text-gray-500">{d.score}/5</span>
                    </div>
                    <ScoreBar score={d.score} />
                    {d.evidenceQuotes.map((q, i) => (
                      <p key={i} className="text-xs text-gray-400 italic mt-1">
                        "{q}"
                      </p>
                    ))}
                    {d.challengeQuestion && <p className="text-xs text-amber-700 mt-1">Challenge: {d.challengeQuestion}</p>}
                  </div>
                ))}
              </div>

              <div>
                <p className="text-xs font-medium text-gray-800 mb-1">Strengths</p>
                <ul className="text-xs text-gray-500 list-disc list-inside space-y-0.5">
                  {review.strengths.map((s, i) => (
                    <li key={i}>{s}</li>
                  ))}
                </ul>
              </div>

              <div>
                <p className="text-xs font-medium text-gray-800 mb-1">Priority fixes</p>
                <ul className="text-xs text-gray-500 list-disc list-inside space-y-0.5">
                  {review.priorityFixes.map((s, i) => (
                    <li key={i}>{s}</li>
                  ))}
                </ul>
              </div>

              {review.consistencyFlags.length > 0 && (
                <div>
                  <p className="text-xs font-medium text-red-700 mb-1">Consistency flags</p>
                  <ul className="text-xs text-red-600 list-disc list-inside space-y-0.5">
                    {review.consistencyFlags.map((s, i) => (
                      <li key={i}>{s}</li>
                    ))}
                  </ul>
                </div>
              )}

              <p className="text-sm text-gray-800 border-t border-gray-100 pt-3">{review.verdict}</p>
            </div>
          )}
        </div>
      )}
    </section>
  )
}
