// GENERATED by premed/pipeline/export-demo-fixtures.ts — do not hand-edit.
// Regenerate with: npm run export-demo-fixtures
import type { CategoryGap } from '../../lib/activity-gap.js'
import type { ApplicantPoolPosition } from '../../lib/corpus-stats.js'
import type { GapAnalysis } from '../../lib/gap-analyzer.js'
import type { PmActivity, PmProfile } from '../../lib/schemas.js'

export type DemoArchetypeFixture = {
  key: string
  profile: PmProfile
  activities: PmActivity[]
  activityGaps: CategoryGap[]
  poolPositions: ApplicantPoolPosition[]
  gapAnalysis: GapAnalysis
}

export const DEMO_ARCHETYPES: DemoArchetypeFixture[] = [
  {
    "key": "grinder",
    "profile": {
      "id": "39c32de3-7358-468a-baae-d1147ef71f57",
      "user_id": "64620492-5eac-4111-86c2-210774b5f001",
      "gpa_cum": 3.9,
      "gpa_science": null,
      "mcat_total": 505,
      "mcat_date": null,
      "state_residence": null,
      "grad_year": null,
      "gap_years": 0,
      "updated_at": "2026-07-03T20:20:56.642+00:00"
    },
    "activities": [
      {
        "id": "7b9f29fa-c431-439f-82ac-e164650e82a3",
        "profile_id": "39c32de3-7358-468a-baae-d1147ef71f57",
        "category": "clinical_volunteer",
        "hours_completed": 150,
        "hours_planned": 0,
        "start_date": null,
        "end_date": null,
        "competencies": null,
        "narrative_theme": null,
        "description": null
      },
      {
        "id": "40ed0370-15fc-4bf7-ac65-2589b44a56df",
        "profile_id": "39c32de3-7358-468a-baae-d1147ef71f57",
        "category": "research",
        "hours_completed": 400,
        "hours_planned": 0,
        "start_date": null,
        "end_date": null,
        "competencies": null,
        "narrative_theme": null,
        "description": null
      }
    ],
    "activityGaps": [
      {
        "category": "clinical_paid",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 300,
          "floor": 150,
          "note": "Paid clinical roles (EMT/scribe/CNA) run higher than volunteer hours since they are employment; 300h+ is the widely-cited competitive range."
        },
        "status": "missing",
        "gapToCompetitive": 300,
        "plannedClosesGap": false
      },
      {
        "category": "nonclinical_volunteer",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 100,
          "floor": 50,
          "note": "Community service outside a clinical setting; 50-100h is the widely-cited range for demonstrating sustained non-clinical commitment."
        },
        "status": "missing",
        "gapToCompetitive": 100,
        "plannedClosesGap": false
      },
      {
        "category": "leadership",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 100,
          "floor": 40,
          "note": "100h+ (roughly 20-50h/year sustained across undergrad) is the widely-cited leadership benchmark; judged more on responsibility/duration than hours."
        },
        "status": "missing",
        "gapToCompetitive": 100,
        "plannedClosesGap": false
      },
      {
        "category": "shadowing",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 75,
          "floor": 40,
          "note": "MedEdits \"75-1-3 rule\" (75h across a primary care physician + 3 specialists) is the most commonly cited target; under 20h is considered risky."
        },
        "status": "missing",
        "gapToCompetitive": 75,
        "plannedClosesGap": false
      },
      {
        "category": "clinical_volunteer",
        "hoursCompleted": 150,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 150,
          "floor": 100,
          "note": "100-150h shows meaningful clinical exposure; 150+ is the widely-cited competitive bar for volunteer (unpaid) clinical roles."
        },
        "status": "strong",
        "gapToCompetitive": 0,
        "plannedClosesGap": null
      },
      {
        "category": "research",
        "hoursCompleted": 400,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 400,
          "floor": 150,
          "note": "400-800h is the widely-cited competitive range for traditional MD applicants (AAMC’s own matriculant average is far higher but skewed by MD-PhD/research-heavy-institution/gap-year applicants)."
        },
        "status": "strong",
        "gapToCompetitive": 0,
        "plannedClosesGap": null
      },
      {
        "category": "teaching",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": null,
          "floor": null,
          "note": "No widely-cited hour benchmark exists for teaching/tutoring; admissions guidance emphasizes communication skill demonstrated, not hours logged."
        },
        "status": null,
        "gapToCompetitive": null,
        "plannedClosesGap": null
      },
      {
        "category": "publication",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": null,
          "floor": null,
          "note": "Publications are a discrete achievement (count), not an hours metric — no hour baseline applies."
        },
        "status": null,
        "gapToCompetitive": null,
        "plannedClosesGap": null
      },
      {
        "category": "extracurricular",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": null,
          "floor": null,
          "note": "Too heterogeneous a catch-all (clubs, sports, hobbies, etc.) for any widely-cited hour norm to exist."
        },
        "status": null,
        "gapToCompetitive": null,
        "plannedClosesGap": null
      },
      {
        "category": "other",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": null,
          "floor": null,
          "note": "Undefined catch-all category — no hour norm applies by definition."
        },
        "status": null,
        "gapToCompetitive": null,
        "plannedClosesGap": null
      }
    ],
    "poolPositions": [
      {
        "cycle_year": 2023,
        "gpa_band": "Greater than 3.79",
        "mcat_band": "502-505",
        "gpa_percentile_applicants": 100,
        "gpa_percentile_acceptees": 100,
        "mcat_percentile_applicants": 41.9,
        "mcat_percentile_acceptees": 17.9,
        "note": "11 cell(s) suppressed on applicants (n<10), 11 cell(s) suppressed on acceptees (n<10) — excluded from this calculation, a small undercount."
      },
      {
        "cycle_year": 2025,
        "gpa_band": "Greater than 3.79",
        "mcat_band": "502-505",
        "gpa_percentile_applicants": 100,
        "gpa_percentile_acceptees": 100,
        "mcat_percentile_applicants": 41.9,
        "mcat_percentile_acceptees": 17.8,
        "note": "13 cell(s) suppressed on applicants (n<10), 13 cell(s) suppressed on acceptees (n<10) — excluded from this calculation, a small undercount."
      }
    ],
    "gapAnalysis": {
      "profile": {
        "gpa": 3.9,
        "mcat": 505
      },
      "gpa_band": "Greater than 3.79",
      "mcat_band": "502-505",
      "neighborBands": {
        "gpaUp": null,
        "gpaDown": "3.60-3.79",
        "mcatUp": "506-509",
        "mcatDown": "498-501"
      },
      "cycles": [
        {
          "cycle_year": 2023,
          "mainCell": {
            "cycle_year": 2023,
            "gpa_band": "Greater than 3.79",
            "mcat_band": "502-505",
            "applicants": 6914,
            "applicants_suppressed": false,
            "acceptees": 2781,
            "acceptees_suppressed": false,
            "acceptance_rate": 40.2,
            "note": null
          },
          "neighbors": {
            "gpaUp": null,
            "gpaDown": {
              "cycle_year": 2023,
              "gpa_band": "3.60-3.79",
              "mcat_band": "502-505",
              "applicants": 6124,
              "applicants_suppressed": false,
              "acceptees": 1962,
              "acceptees_suppressed": false,
              "acceptance_rate": 32,
              "note": null
            },
            "mcatUp": {
              "cycle_year": 2023,
              "gpa_band": "Greater than 3.79",
              "mcat_band": "506-509",
              "applicants": 9948,
              "applicants_suppressed": false,
              "acceptees": 5208,
              "acceptees_suppressed": false,
              "acceptance_rate": 52.4,
              "note": null
            },
            "mcatDown": {
              "cycle_year": 2023,
              "gpa_band": "Greater than 3.79",
              "mcat_band": "498-501",
              "applicants": 3826,
              "applicants_suppressed": false,
              "acceptees": 1105,
              "acceptees_suppressed": false,
              "acceptance_rate": 28.9,
              "note": null
            }
          }
        },
        {
          "cycle_year": 2025,
          "mainCell": {
            "cycle_year": 2025,
            "gpa_band": "Greater than 3.79",
            "mcat_band": "502-505",
            "applicants": 7428,
            "applicants_suppressed": false,
            "acceptees": 3333,
            "acceptees_suppressed": false,
            "acceptance_rate": 44.9,
            "note": null
          },
          "neighbors": {
            "gpaUp": null,
            "gpaDown": {
              "cycle_year": 2025,
              "gpa_band": "3.60-3.79",
              "mcat_band": "502-505",
              "applicants": 5873,
              "applicants_suppressed": false,
              "acceptees": 2037,
              "acceptees_suppressed": false,
              "acceptance_rate": 34.7,
              "note": null
            },
            "mcatUp": {
              "cycle_year": 2025,
              "gpa_band": "Greater than 3.79",
              "mcat_band": "506-509",
              "applicants": 10817,
              "applicants_suppressed": false,
              "acceptees": 6173,
              "acceptees_suppressed": false,
              "acceptance_rate": 57.1,
              "note": null
            },
            "mcatDown": {
              "cycle_year": 2025,
              "gpa_band": "Greater than 3.79",
              "mcat_band": "498-501",
              "applicants": 4125,
              "applicants_suppressed": false,
              "acceptees": 1264,
              "acceptees_suppressed": false,
              "acceptance_rate": 30.6,
              "note": null
            }
          }
        }
      ],
      "delta": {
        "from_cycle_year": 2023,
        "to_cycle_year": 2025,
        "applicants_delta": 514,
        "acceptees_delta": 552,
        "acceptance_rate_delta": 4.7,
        "note": null
      }
    }
  },
  {
    "key": "flipped",
    "profile": {
      "id": "5f0f35e4-6f7d-4ab7-a476-db0e655cea83",
      "user_id": "3b92baf1-c5e1-47c6-a6aa-7bd110fb5a18",
      "gpa_cum": 3.4,
      "gpa_science": null,
      "mcat_total": 517,
      "mcat_date": null,
      "state_residence": null,
      "grad_year": null,
      "gap_years": 0,
      "updated_at": "2026-07-03T20:20:57.05+00:00"
    },
    "activities": [
      {
        "id": "65713b7c-209b-441d-9158-ce9dca1d7f1a",
        "profile_id": "5f0f35e4-6f7d-4ab7-a476-db0e655cea83",
        "category": "clinical_paid",
        "hours_completed": 800,
        "hours_planned": 0,
        "start_date": null,
        "end_date": null,
        "competencies": null,
        "narrative_theme": null,
        "description": null
      },
      {
        "id": "1af7f160-2c0e-4f6a-8676-00a55948f943",
        "profile_id": "5f0f35e4-6f7d-4ab7-a476-db0e655cea83",
        "category": "research",
        "hours_completed": 50,
        "hours_planned": 0,
        "start_date": null,
        "end_date": null,
        "competencies": null,
        "narrative_theme": null,
        "description": null
      }
    ],
    "activityGaps": [
      {
        "category": "research",
        "hoursCompleted": 50,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 400,
          "floor": 150,
          "note": "400-800h is the widely-cited competitive range for traditional MD applicants (AAMC’s own matriculant average is far higher but skewed by MD-PhD/research-heavy-institution/gap-year applicants)."
        },
        "status": "below",
        "gapToCompetitive": 350,
        "plannedClosesGap": false
      },
      {
        "category": "clinical_volunteer",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 150,
          "floor": 100,
          "note": "100-150h shows meaningful clinical exposure; 150+ is the widely-cited competitive bar for volunteer (unpaid) clinical roles."
        },
        "status": "missing",
        "gapToCompetitive": 150,
        "plannedClosesGap": false
      },
      {
        "category": "nonclinical_volunteer",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 100,
          "floor": 50,
          "note": "Community service outside a clinical setting; 50-100h is the widely-cited range for demonstrating sustained non-clinical commitment."
        },
        "status": "missing",
        "gapToCompetitive": 100,
        "plannedClosesGap": false
      },
      {
        "category": "leadership",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 100,
          "floor": 40,
          "note": "100h+ (roughly 20-50h/year sustained across undergrad) is the widely-cited leadership benchmark; judged more on responsibility/duration than hours."
        },
        "status": "missing",
        "gapToCompetitive": 100,
        "plannedClosesGap": false
      },
      {
        "category": "shadowing",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 75,
          "floor": 40,
          "note": "MedEdits \"75-1-3 rule\" (75h across a primary care physician + 3 specialists) is the most commonly cited target; under 20h is considered risky."
        },
        "status": "missing",
        "gapToCompetitive": 75,
        "plannedClosesGap": false
      },
      {
        "category": "clinical_paid",
        "hoursCompleted": 800,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 300,
          "floor": 150,
          "note": "Paid clinical roles (EMT/scribe/CNA) run higher than volunteer hours since they are employment; 300h+ is the widely-cited competitive range."
        },
        "status": "strong",
        "gapToCompetitive": 0,
        "plannedClosesGap": null
      },
      {
        "category": "teaching",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": null,
          "floor": null,
          "note": "No widely-cited hour benchmark exists for teaching/tutoring; admissions guidance emphasizes communication skill demonstrated, not hours logged."
        },
        "status": null,
        "gapToCompetitive": null,
        "plannedClosesGap": null
      },
      {
        "category": "publication",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": null,
          "floor": null,
          "note": "Publications are a discrete achievement (count), not an hours metric — no hour baseline applies."
        },
        "status": null,
        "gapToCompetitive": null,
        "plannedClosesGap": null
      },
      {
        "category": "extracurricular",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": null,
          "floor": null,
          "note": "Too heterogeneous a catch-all (clubs, sports, hobbies, etc.) for any widely-cited hour norm to exist."
        },
        "status": null,
        "gapToCompetitive": null,
        "plannedClosesGap": null
      },
      {
        "category": "other",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": null,
          "floor": null,
          "note": "Undefined catch-all category — no hour norm applies by definition."
        },
        "status": null,
        "gapToCompetitive": null,
        "plannedClosesGap": null
      }
    ],
    "poolPositions": [
      {
        "cycle_year": 2023,
        "gpa_band": "3.40-3.59",
        "mcat_band": "514-517",
        "gpa_percentile_applicants": 37.7,
        "gpa_percentile_acceptees": 20.7,
        "mcat_percentile_applicants": 89,
        "mcat_percentile_acceptees": 79.5,
        "note": "11 cell(s) suppressed on applicants (n<10), 11 cell(s) suppressed on acceptees (n<10) — excluded from this calculation, a small undercount."
      },
      {
        "cycle_year": 2025,
        "gpa_band": "3.40-3.59",
        "mcat_band": "514-517",
        "gpa_percentile_applicants": 32.6,
        "gpa_percentile_acceptees": 16,
        "mcat_percentile_applicants": 88.4,
        "mcat_percentile_acceptees": 79.4,
        "note": "13 cell(s) suppressed on applicants (n<10), 13 cell(s) suppressed on acceptees (n<10) — excluded from this calculation, a small undercount."
      }
    ],
    "gapAnalysis": {
      "profile": {
        "gpa": 3.4,
        "mcat": 517
      },
      "gpa_band": "3.40-3.59",
      "mcat_band": "514-517",
      "neighborBands": {
        "gpaUp": "3.60-3.79",
        "gpaDown": "3.20-3.39",
        "mcatUp": "Greater than 517",
        "mcatDown": "510-513"
      },
      "cycles": [
        {
          "cycle_year": 2023,
          "mainCell": {
            "cycle_year": 2023,
            "gpa_band": "3.40-3.59",
            "mcat_band": "514-517",
            "applicants": 2624,
            "applicants_suppressed": false,
            "acceptees": 1476,
            "acceptees_suppressed": false,
            "acceptance_rate": 56.3,
            "note": null
          },
          "neighbors": {
            "gpaUp": {
              "cycle_year": 2023,
              "gpa_band": "3.60-3.79",
              "mcat_band": "514-517",
              "applicants": 5678,
              "applicants_suppressed": false,
              "acceptees": 3711,
              "acceptees_suppressed": false,
              "acceptance_rate": 65.4,
              "note": null
            },
            "gpaDown": {
              "cycle_year": 2023,
              "gpa_band": "3.20-3.39",
              "mcat_band": "514-517",
              "applicants": 1091,
              "applicants_suppressed": false,
              "acceptees": 522,
              "acceptees_suppressed": false,
              "acceptance_rate": 47.8,
              "note": null
            },
            "mcatUp": {
              "cycle_year": 2023,
              "gpa_band": "3.40-3.59",
              "mcat_band": "Greater than 517",
              "applicants": 1194,
              "applicants_suppressed": false,
              "acceptees": 733,
              "acceptees_suppressed": false,
              "acceptance_rate": 61.4,
              "note": null
            },
            "mcatDown": {
              "cycle_year": 2023,
              "gpa_band": "3.40-3.59",
              "mcat_band": "510-513",
              "applicants": 4290,
              "applicants_suppressed": false,
              "acceptees": 1945,
              "acceptees_suppressed": false,
              "acceptance_rate": 45.3,
              "note": null
            }
          }
        },
        {
          "cycle_year": 2025,
          "mainCell": {
            "cycle_year": 2025,
            "gpa_band": "3.40-3.59",
            "mcat_band": "514-517",
            "applicants": 1851,
            "applicants_suppressed": false,
            "acceptees": 1046,
            "acceptees_suppressed": false,
            "acceptance_rate": 56.5,
            "note": null
          },
          "neighbors": {
            "gpaUp": {
              "cycle_year": 2025,
              "gpa_band": "3.60-3.79",
              "mcat_band": "514-517",
              "applicants": 4744,
              "applicants_suppressed": false,
              "acceptees": 3165,
              "acceptees_suppressed": false,
              "acceptance_rate": 66.7,
              "note": null
            },
            "gpaDown": {
              "cycle_year": 2025,
              "gpa_band": "3.20-3.39",
              "mcat_band": "514-517",
              "applicants": 694,
              "applicants_suppressed": false,
              "acceptees": 316,
              "acceptees_suppressed": false,
              "acceptance_rate": 45.5,
              "note": null
            },
            "mcatUp": {
              "cycle_year": 2025,
              "gpa_band": "3.40-3.59",
              "mcat_band": "Greater than 517",
              "applicants": 865,
              "applicants_suppressed": false,
              "acceptees": 574,
              "acceptees_suppressed": false,
              "acceptance_rate": 66.4,
              "note": null
            },
            "mcatDown": {
              "cycle_year": 2025,
              "gpa_band": "3.40-3.59",
              "mcat_band": "510-513",
              "applicants": 3100,
              "applicants_suppressed": false,
              "acceptees": 1510,
              "acceptees_suppressed": false,
              "acceptance_rate": 48.7,
              "note": null
            }
          }
        }
      ],
      "delta": {
        "from_cycle_year": 2023,
        "to_cycle_year": 2025,
        "applicants_delta": -773,
        "acceptees_delta": -430,
        "acceptance_rate_delta": 0.2,
        "note": null
      }
    }
  },
  {
    "key": "balanced",
    "profile": {
      "id": "10ace929-96d3-45c8-95d1-b11e92bfbb3e",
      "user_id": "430e8e4a-b0d4-4aae-bb38-5993289ff9c0",
      "gpa_cum": 3.6,
      "gpa_science": null,
      "mcat_total": 508,
      "mcat_date": null,
      "state_residence": null,
      "grad_year": null,
      "gap_years": 0,
      "updated_at": "2026-07-03T20:20:57.437+00:00"
    },
    "activities": [
      {
        "id": "55937e3c-eb8c-4215-b02b-bdc21ba1e9b4",
        "profile_id": "10ace929-96d3-45c8-95d1-b11e92bfbb3e",
        "category": "clinical_volunteer",
        "hours_completed": 200,
        "hours_planned": 0,
        "start_date": null,
        "end_date": null,
        "competencies": null,
        "narrative_theme": null,
        "description": null
      },
      {
        "id": "9073bfd7-ef1e-4de6-baf0-84a66b15b7dc",
        "profile_id": "10ace929-96d3-45c8-95d1-b11e92bfbb3e",
        "category": "nonclinical_volunteer",
        "hours_completed": 100,
        "hours_planned": 0,
        "start_date": null,
        "end_date": null,
        "competencies": null,
        "narrative_theme": null,
        "description": null
      },
      {
        "id": "7b27a3db-0a7c-4eb3-ab1e-1a1192628440",
        "profile_id": "10ace929-96d3-45c8-95d1-b11e92bfbb3e",
        "category": "research",
        "hours_completed": 200,
        "hours_planned": 0,
        "start_date": null,
        "end_date": null,
        "competencies": null,
        "narrative_theme": null,
        "description": null
      }
    ],
    "activityGaps": [
      {
        "category": "clinical_paid",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 300,
          "floor": 150,
          "note": "Paid clinical roles (EMT/scribe/CNA) run higher than volunteer hours since they are employment; 300h+ is the widely-cited competitive range."
        },
        "status": "missing",
        "gapToCompetitive": 300,
        "plannedClosesGap": false
      },
      {
        "category": "research",
        "hoursCompleted": 200,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 400,
          "floor": 150,
          "note": "400-800h is the widely-cited competitive range for traditional MD applicants (AAMC’s own matriculant average is far higher but skewed by MD-PhD/research-heavy-institution/gap-year applicants)."
        },
        "status": "competitive",
        "gapToCompetitive": 200,
        "plannedClosesGap": false
      },
      {
        "category": "leadership",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 100,
          "floor": 40,
          "note": "100h+ (roughly 20-50h/year sustained across undergrad) is the widely-cited leadership benchmark; judged more on responsibility/duration than hours."
        },
        "status": "missing",
        "gapToCompetitive": 100,
        "plannedClosesGap": false
      },
      {
        "category": "shadowing",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 75,
          "floor": 40,
          "note": "MedEdits \"75-1-3 rule\" (75h across a primary care physician + 3 specialists) is the most commonly cited target; under 20h is considered risky."
        },
        "status": "missing",
        "gapToCompetitive": 75,
        "plannedClosesGap": false
      },
      {
        "category": "clinical_volunteer",
        "hoursCompleted": 200,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 150,
          "floor": 100,
          "note": "100-150h shows meaningful clinical exposure; 150+ is the widely-cited competitive bar for volunteer (unpaid) clinical roles."
        },
        "status": "strong",
        "gapToCompetitive": 0,
        "plannedClosesGap": null
      },
      {
        "category": "nonclinical_volunteer",
        "hoursCompleted": 100,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 100,
          "floor": 50,
          "note": "Community service outside a clinical setting; 50-100h is the widely-cited range for demonstrating sustained non-clinical commitment."
        },
        "status": "strong",
        "gapToCompetitive": 0,
        "plannedClosesGap": null
      },
      {
        "category": "teaching",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": null,
          "floor": null,
          "note": "No widely-cited hour benchmark exists for teaching/tutoring; admissions guidance emphasizes communication skill demonstrated, not hours logged."
        },
        "status": null,
        "gapToCompetitive": null,
        "plannedClosesGap": null
      },
      {
        "category": "publication",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": null,
          "floor": null,
          "note": "Publications are a discrete achievement (count), not an hours metric — no hour baseline applies."
        },
        "status": null,
        "gapToCompetitive": null,
        "plannedClosesGap": null
      },
      {
        "category": "extracurricular",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": null,
          "floor": null,
          "note": "Too heterogeneous a catch-all (clubs, sports, hobbies, etc.) for any widely-cited hour norm to exist."
        },
        "status": null,
        "gapToCompetitive": null,
        "plannedClosesGap": null
      },
      {
        "category": "other",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": null,
          "floor": null,
          "note": "Undefined catch-all category — no hour norm applies by definition."
        },
        "status": null,
        "gapToCompetitive": null,
        "plannedClosesGap": null
      }
    ],
    "poolPositions": [
      {
        "cycle_year": 2023,
        "gpa_band": "3.60-3.79",
        "mcat_band": "506-509",
        "gpa_percentile_applicants": 62.6,
        "gpa_percentile_acceptees": 45.6,
        "mcat_percentile_applicants": 58.5,
        "mcat_percentile_acceptees": 34.4,
        "note": "11 cell(s) suppressed on applicants (n<10), 11 cell(s) suppressed on acceptees (n<10) — excluded from this calculation, a small undercount."
      },
      {
        "cycle_year": 2025,
        "gpa_band": "3.60-3.79",
        "mcat_band": "506-509",
        "gpa_percentile_applicants": 56.5,
        "gpa_percentile_acceptees": 38.5,
        "mcat_percentile_applicants": 57.9,
        "mcat_percentile_acceptees": 34.6,
        "note": "13 cell(s) suppressed on applicants (n<10), 13 cell(s) suppressed on acceptees (n<10) — excluded from this calculation, a small undercount."
      }
    ],
    "gapAnalysis": {
      "profile": {
        "gpa": 3.6,
        "mcat": 508
      },
      "gpa_band": "3.60-3.79",
      "mcat_band": "506-509",
      "neighborBands": {
        "gpaUp": "Greater than 3.79",
        "gpaDown": "3.40-3.59",
        "mcatUp": "510-513",
        "mcatDown": "502-505"
      },
      "cycles": [
        {
          "cycle_year": 2023,
          "mainCell": {
            "cycle_year": 2023,
            "gpa_band": "3.60-3.79",
            "mcat_band": "506-509",
            "applicants": 7836,
            "applicants_suppressed": false,
            "acceptees": 3167,
            "acceptees_suppressed": false,
            "acceptance_rate": 40.4,
            "note": null
          },
          "neighbors": {
            "gpaUp": {
              "cycle_year": 2023,
              "gpa_band": "Greater than 3.79",
              "mcat_band": "506-509",
              "applicants": 9948,
              "applicants_suppressed": false,
              "acceptees": 5208,
              "acceptees_suppressed": false,
              "acceptance_rate": 52.4,
              "note": null
            },
            "gpaDown": {
              "cycle_year": 2023,
              "gpa_band": "3.40-3.59",
              "mcat_band": "506-509",
              "applicants": 5001,
              "applicants_suppressed": false,
              "acceptees": 1686,
              "acceptees_suppressed": false,
              "acceptance_rate": 33.7,
              "note": null
            },
            "mcatUp": {
              "cycle_year": 2023,
              "gpa_band": "3.60-3.79",
              "mcat_band": "510-513",
              "applicants": 8005,
              "applicants_suppressed": false,
              "acceptees": 4538,
              "acceptees_suppressed": false,
              "acceptance_rate": 56.7,
              "note": null
            },
            "mcatDown": {
              "cycle_year": 2023,
              "gpa_band": "3.60-3.79",
              "mcat_band": "502-505",
              "applicants": 6124,
              "applicants_suppressed": false,
              "acceptees": 1962,
              "acceptees_suppressed": false,
              "acceptance_rate": 32,
              "note": null
            }
          }
        },
        {
          "cycle_year": 2025,
          "mainCell": {
            "cycle_year": 2025,
            "gpa_band": "3.60-3.79",
            "mcat_band": "506-509",
            "applicants": 7069,
            "applicants_suppressed": false,
            "acceptees": 3212,
            "acceptees_suppressed": false,
            "acceptance_rate": 45.4,
            "note": null
          },
          "neighbors": {
            "gpaUp": {
              "cycle_year": 2025,
              "gpa_band": "Greater than 3.79",
              "mcat_band": "506-509",
              "applicants": 10817,
              "applicants_suppressed": false,
              "acceptees": 6173,
              "acceptees_suppressed": false,
              "acceptance_rate": 57.1,
              "note": null
            },
            "gpaDown": {
              "cycle_year": 2025,
              "gpa_band": "3.40-3.59",
              "mcat_band": "506-509",
              "applicants": 3947,
              "applicants_suppressed": false,
              "acceptees": 1450,
              "acceptees_suppressed": false,
              "acceptance_rate": 36.7,
              "note": null
            },
            "mcatUp": {
              "cycle_year": 2025,
              "gpa_band": "3.60-3.79",
              "mcat_band": "510-513",
              "applicants": 6940,
              "applicants_suppressed": false,
              "acceptees": 4167,
              "acceptees_suppressed": false,
              "acceptance_rate": 60,
              "note": null
            },
            "mcatDown": {
              "cycle_year": 2025,
              "gpa_band": "3.60-3.79",
              "mcat_band": "502-505",
              "applicants": 5873,
              "applicants_suppressed": false,
              "acceptees": 2037,
              "acceptees_suppressed": false,
              "acceptance_rate": 34.7,
              "note": null
            }
          }
        }
      ],
      "delta": {
        "from_cycle_year": 2023,
        "to_cycle_year": 2025,
        "applicants_delta": -767,
        "acceptees_delta": 45,
        "acceptance_rate_delta": 5,
        "note": null
      }
    }
  },
  {
    "key": "climber",
    "profile": {
      "id": "d5a5c99c-df96-4e2d-b452-41bbfa931bcc",
      "user_id": "815b38d9-7539-4f97-80ce-40a71a3f6293",
      "gpa_cum": 3.2,
      "gpa_science": null,
      "mcat_total": 512,
      "mcat_date": null,
      "state_residence": null,
      "grad_year": null,
      "gap_years": 2,
      "updated_at": "2026-07-03T20:20:57.911+00:00"
    },
    "activities": [
      {
        "id": "fd6b54df-2469-4467-be17-451280333841",
        "profile_id": "d5a5c99c-df96-4e2d-b452-41bbfa931bcc",
        "category": "clinical_paid",
        "hours_completed": 2000,
        "hours_planned": 0,
        "start_date": null,
        "end_date": null,
        "competencies": null,
        "narrative_theme": null,
        "description": null
      },
      {
        "id": "5a3a543a-5295-4388-8305-9c3325d3adeb",
        "profile_id": "d5a5c99c-df96-4e2d-b452-41bbfa931bcc",
        "category": "leadership",
        "hours_completed": 300,
        "hours_planned": 0,
        "start_date": null,
        "end_date": null,
        "competencies": null,
        "narrative_theme": null,
        "description": null
      }
    ],
    "activityGaps": [
      {
        "category": "research",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 400,
          "floor": 150,
          "note": "400-800h is the widely-cited competitive range for traditional MD applicants (AAMC’s own matriculant average is far higher but skewed by MD-PhD/research-heavy-institution/gap-year applicants)."
        },
        "status": "missing",
        "gapToCompetitive": 400,
        "plannedClosesGap": false
      },
      {
        "category": "clinical_volunteer",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 150,
          "floor": 100,
          "note": "100-150h shows meaningful clinical exposure; 150+ is the widely-cited competitive bar for volunteer (unpaid) clinical roles."
        },
        "status": "missing",
        "gapToCompetitive": 150,
        "plannedClosesGap": false
      },
      {
        "category": "nonclinical_volunteer",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 100,
          "floor": 50,
          "note": "Community service outside a clinical setting; 50-100h is the widely-cited range for demonstrating sustained non-clinical commitment."
        },
        "status": "missing",
        "gapToCompetitive": 100,
        "plannedClosesGap": false
      },
      {
        "category": "shadowing",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 75,
          "floor": 40,
          "note": "MedEdits \"75-1-3 rule\" (75h across a primary care physician + 3 specialists) is the most commonly cited target; under 20h is considered risky."
        },
        "status": "missing",
        "gapToCompetitive": 75,
        "plannedClosesGap": false
      },
      {
        "category": "clinical_paid",
        "hoursCompleted": 2000,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 300,
          "floor": 150,
          "note": "Paid clinical roles (EMT/scribe/CNA) run higher than volunteer hours since they are employment; 300h+ is the widely-cited competitive range."
        },
        "status": "strong",
        "gapToCompetitive": 0,
        "plannedClosesGap": null
      },
      {
        "category": "leadership",
        "hoursCompleted": 300,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": 100,
          "floor": 40,
          "note": "100h+ (roughly 20-50h/year sustained across undergrad) is the widely-cited leadership benchmark; judged more on responsibility/duration than hours."
        },
        "status": "strong",
        "gapToCompetitive": 0,
        "plannedClosesGap": null
      },
      {
        "category": "teaching",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": null,
          "floor": null,
          "note": "No widely-cited hour benchmark exists for teaching/tutoring; admissions guidance emphasizes communication skill demonstrated, not hours logged."
        },
        "status": null,
        "gapToCompetitive": null,
        "plannedClosesGap": null
      },
      {
        "category": "publication",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": null,
          "floor": null,
          "note": "Publications are a discrete achievement (count), not an hours metric — no hour baseline applies."
        },
        "status": null,
        "gapToCompetitive": null,
        "plannedClosesGap": null
      },
      {
        "category": "extracurricular",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": null,
          "floor": null,
          "note": "Too heterogeneous a catch-all (clubs, sports, hobbies, etc.) for any widely-cited hour norm to exist."
        },
        "status": null,
        "gapToCompetitive": null,
        "plannedClosesGap": null
      },
      {
        "category": "other",
        "hoursCompleted": 0,
        "hoursPlanned": 0,
        "baseline": {
          "competitive": null,
          "floor": null,
          "note": "Undefined catch-all category — no hour norm applies by definition."
        },
        "status": null,
        "gapToCompetitive": null,
        "plannedClosesGap": null
      }
    ],
    "poolPositions": [
      {
        "cycle_year": 2023,
        "gpa_band": "3.20-3.39",
        "mcat_band": "510-513",
        "gpa_percentile_applicants": 21.4,
        "gpa_percentile_acceptees": 9.1,
        "mcat_percentile_applicants": 75.7,
        "mcat_percentile_acceptees": 57.8,
        "note": "11 cell(s) suppressed on applicants (n<10), 11 cell(s) suppressed on acceptees (n<10) — excluded from this calculation, a small undercount."
      },
      {
        "cycle_year": 2025,
        "gpa_band": "3.20-3.39",
        "mcat_band": "510-513",
        "gpa_percentile_applicants": 18.2,
        "gpa_percentile_acceptees": 6.6,
        "mcat_percentile_applicants": 74.8,
        "mcat_percentile_acceptees": 57.9,
        "note": "13 cell(s) suppressed on applicants (n<10), 13 cell(s) suppressed on acceptees (n<10) — excluded from this calculation, a small undercount."
      }
    ],
    "gapAnalysis": {
      "profile": {
        "gpa": 3.2,
        "mcat": 512
      },
      "gpa_band": "3.20-3.39",
      "mcat_band": "510-513",
      "neighborBands": {
        "gpaUp": "3.40-3.59",
        "gpaDown": "3.00-3.19",
        "mcatUp": "514-517",
        "mcatDown": "506-509"
      },
      "cycles": [
        {
          "cycle_year": 2023,
          "mainCell": {
            "cycle_year": 2023,
            "gpa_band": "3.20-3.39",
            "mcat_band": "510-513",
            "applicants": 2043,
            "applicants_suppressed": false,
            "acceptees": 838,
            "acceptees_suppressed": false,
            "acceptance_rate": 41,
            "note": null
          },
          "neighbors": {
            "gpaUp": {
              "cycle_year": 2023,
              "gpa_band": "3.40-3.59",
              "mcat_band": "510-513",
              "applicants": 4290,
              "applicants_suppressed": false,
              "acceptees": 1945,
              "acceptees_suppressed": false,
              "acceptance_rate": 45.3,
              "note": null
            },
            "gpaDown": {
              "cycle_year": 2023,
              "gpa_band": "3.00-3.19",
              "mcat_band": "510-513",
              "applicants": 919,
              "applicants_suppressed": false,
              "acceptees": 314,
              "acceptees_suppressed": false,
              "acceptance_rate": 34.2,
              "note": null
            },
            "mcatUp": {
              "cycle_year": 2023,
              "gpa_band": "3.20-3.39",
              "mcat_band": "514-517",
              "applicants": 1091,
              "applicants_suppressed": false,
              "acceptees": 522,
              "acceptees_suppressed": false,
              "acceptance_rate": 47.8,
              "note": null
            },
            "mcatDown": {
              "cycle_year": 2023,
              "gpa_band": "3.20-3.39",
              "mcat_band": "506-509",
              "applicants": 2505,
              "applicants_suppressed": false,
              "acceptees": 793,
              "acceptees_suppressed": false,
              "acceptance_rate": 31.7,
              "note": null
            }
          }
        },
        {
          "cycle_year": 2025,
          "mainCell": {
            "cycle_year": 2025,
            "gpa_band": "3.20-3.39",
            "mcat_band": "510-513",
            "applicants": 1344,
            "applicants_suppressed": false,
            "acceptees": 569,
            "acceptees_suppressed": false,
            "acceptance_rate": 42.3,
            "note": null
          },
          "neighbors": {
            "gpaUp": {
              "cycle_year": 2025,
              "gpa_band": "3.40-3.59",
              "mcat_band": "510-513",
              "applicants": 3100,
              "applicants_suppressed": false,
              "acceptees": 1510,
              "acceptees_suppressed": false,
              "acceptance_rate": 48.7,
              "note": null
            },
            "gpaDown": {
              "cycle_year": 2025,
              "gpa_band": "3.00-3.19",
              "mcat_band": "510-513",
              "applicants": 649,
              "applicants_suppressed": false,
              "acceptees": 243,
              "acceptees_suppressed": false,
              "acceptance_rate": 37.4,
              "note": null
            },
            "mcatUp": {
              "cycle_year": 2025,
              "gpa_band": "3.20-3.39",
              "mcat_band": "514-517",
              "applicants": 694,
              "applicants_suppressed": false,
              "acceptees": 316,
              "acceptees_suppressed": false,
              "acceptance_rate": 45.5,
              "note": null
            },
            "mcatDown": {
              "cycle_year": 2025,
              "gpa_band": "3.20-3.39",
              "mcat_band": "506-509",
              "applicants": 1752,
              "applicants_suppressed": false,
              "acceptees": 557,
              "acceptees_suppressed": false,
              "acceptance_rate": 31.8,
              "note": null
            }
          }
        }
      ],
      "delta": {
        "from_cycle_year": 2023,
        "to_cycle_year": 2025,
        "applicants_delta": -699,
        "acceptees_delta": -269,
        "acceptance_rate_delta": 1.3,
        "note": null
      }
    }
  }
]
