// GENERATED by premed/pipeline/export-demo-fixtures.ts — do not hand-edit.
// Regenerate with: npm run export-demo-fixtures
import type { SchoolStatsRow } from '../../lib/school-comparison.js'

export const SCHOOL_STATS_SNAPSHOT: SchoolStatsRow[] = [
  {
    "school_id": "1c7a9db8-b28d-4218-bc85-3016c8703a28",
    "school_name": "Perelman School of Medicine at the University of Pennsylvania",
    "cycle_year": 2026,
    "median_gpa": 3.96,
    "median_mcat": 521
  },
  {
    "school_id": "ad24f99b-a921-4466-8da0-21ecc79a93e4",
    "school_name": "Washington University School of Medicine in St. Louis",
    "cycle_year": 2025,
    "median_gpa": 3.88,
    "median_mcat": 520
  },
  {
    "school_id": "dfc5dc2e-213b-4c6d-9c42-e81bfec37ab3",
    "school_name": "LSU Health Shreveport School of Medicine",
    "cycle_year": 2026,
    "median_gpa": 3.77,
    "median_mcat": 507
  },
  {
    "school_id": "eac7ae11-7c01-4f6f-8fa8-47da536d024f",
    "school_name": "Tulane University School of Medicine",
    "cycle_year": 2029,
    "median_gpa": 3.7,
    "median_mcat": 510
  },
  {
    "school_id": "4e1ee328-3738-4fcc-ae06-bfaf9f412558",
    "school_name": "UT Southwestern Medical School",
    "cycle_year": 2028,
    "median_gpa": 3.89,
    "median_mcat": 516
  },
  {
    "school_id": "7f348766-573c-4abd-85ba-6cf23ed5929c",
    "school_name": "The Ohio State University College of Medicine",
    "cycle_year": 2025,
    "median_gpa": 3.83,
    "median_mcat": 514
  },
  {
    "school_id": "da405ab8-c6ba-40b4-b3f9-b74082318687",
    "school_name": "University of Wisconsin School of Medicine and Public Health",
    "cycle_year": 2025,
    "median_gpa": 3.78,
    "median_mcat": 511
  },
  {
    "school_id": "5c5a2f3b-064c-45a1-8b04-6b00acd2bc88",
    "school_name": "Tufts University School of Medicine",
    "cycle_year": 2029,
    "median_gpa": 3.82,
    "median_mcat": 514
  },
  {
    "school_id": "8f85dd39-f8b3-477f-a63b-ca196725fd81",
    "school_name": "Chicago Medical School at Rosalind Franklin University",
    "cycle_year": 2025,
    "median_gpa": 3.69,
    "median_mcat": 508
  },
  {
    "school_id": "75d2115b-cb4b-473e-8f97-df2d64ab4957",
    "school_name": "Wake Forest University School of Medicine",
    "cycle_year": 2029,
    "median_gpa": 3.81,
    "median_mcat": 511
  },
  {
    "school_id": "b95a8618-714e-436a-b0f4-51c20dfb6a90",
    "school_name": "Morehouse School of Medicine",
    "cycle_year": 2025,
    "median_gpa": 3.64,
    "median_mcat": 506
  },
  {
    "school_id": "882f6a44-144f-4ed5-a682-6053d95359ac",
    "school_name": "Creighton University School of Medicine",
    "cycle_year": 2029,
    "median_gpa": 3.86,
    "median_mcat": 513
  }
]
