import type { SupabaseClient } from '@supabase/supabase-js'

export type SchoolStatsRow = {
  school_id: string
  school_name: string
  cycle_year: number
  median_gpa: number
  median_mcat: number
}

export type SchoolComparisonRow = SchoolStatsRow & {
  /** yours - theirs */
  gpa_delta: number
  mcat_delta: number
  fit_category: 'reach' | 'target' | 'safety'
  /** Higher = safer fit (you're further above their median on both metrics). */
  fit_score: number
}

// Roughly one AAMC band width in each dimension (GPA bands run ~0.20 wide,
// MCAT bands mostly 4 points), used to bring the two deltas onto a
// comparable scale before combining them into a single fit_score.
const GPA_NORMALIZER = 0.2
const MCAT_NORMALIZER = 4

export function classifyFit(gpaDelta: number, mcatDelta: number): 'reach' | 'target' | 'safety' {
  const gpaAtOrAbove = gpaDelta >= 0
  const mcatAtOrAbove = mcatDelta >= 0
  if (gpaAtOrAbove && mcatAtOrAbove) return 'safety'
  if (!gpaAtOrAbove && !mcatAtOrAbove) return 'reach'
  return 'target'
}

/**
 * Pure comparison math — no network access, works identically whether the
 * `schools` array came from a live service-role query or a pre-generated
 * static snapshot (see `loadSchoolStatsRows` below for why the browser needs
 * the latter). Sorted safest-fit first.
 */
export function computeSchoolComparison(
  schools: SchoolStatsRow[],
  profile: { gpa: number; mcat: number }
): SchoolComparisonRow[] {
  const rows = schools.map(school => {
    const gpa_delta = Math.round((profile.gpa - school.median_gpa) * 100) / 100
    const mcat_delta = profile.mcat - school.median_mcat
    const fit_category = classifyFit(gpa_delta, mcat_delta)
    const fit_score = Math.round((gpa_delta / GPA_NORMALIZER + mcat_delta / MCAT_NORMALIZER) * 100) / 100
    return { ...school, gpa_delta, mcat_delta, fit_category, fit_score }
  })
  return rows.sort((a, b) => b.fit_score - a.fit_score)
}

/**
 * pm_school_stats has RLS enabled with ZERO policies (session 1 — "pending
 * source license review"), unlike pm_schools/pm_facts_grid which are
 * public-read. It was populated with real scraped class-profile data in
 * session 5, but its RLS tier was never revisited (no schema changes this
 * session either). So this function only ever works with a service-role
 * client — it's the server-side half of the split documented in
 * docs/handoffs/2026-07-03-premed-session-7.md. The browser instead imports
 * a static JSON snapshot (generated by premed/pipeline/export-demo-fixtures.ts)
 * and calls `computeSchoolComparison` directly on it.
 */
export async function loadSchoolStatsRows(supabase: SupabaseClient): Promise<SchoolStatsRow[]> {
  const { data, error } = await supabase
    .from('pm_school_stats')
    .select('school_id, cycle_year, median_gpa, median_mcat, pm_schools(name)')
    .not('median_gpa', 'is', null)
    .not('median_mcat', 'is', null)
  if (error) throw new Error(`Failed to load pm_school_stats: ${error.message}`)

  return (data ?? []).map((row: Record<string, unknown>) => ({
    school_id: row.school_id as string,
    school_name: ((row.pm_schools as { name?: string } | null)?.name ?? 'Unknown school'),
    cycle_year: row.cycle_year as number,
    median_gpa: row.median_gpa as number,
    median_mcat: row.median_mcat as number,
  }))
}

export type MissionFitSchool = { name: string; mission_keywords: string[] | null }

/**
 * Fuzzy `ilike` lookup against `pm_schools.name` — first match wins, since the
 * table has no unique constraint on name. Fine for a single-operator CLI and
 * a single logged-in dashboard user; would need tightening (exact id, or
 * disambiguation on multiple matches) before any multi-user surface used it.
 * Shared by the CLI and the review-essay Edge Function.
 */
export async function findSchool(supabase: SupabaseClient, nameQuery: string): Promise<MissionFitSchool | null> {
  const { data, error } = await supabase.from('pm_schools').select('name, mission_keywords').ilike('name', `%${nameQuery}%`).limit(1)
  if (error) throw new Error(`Failed to look up school "${nameQuery}": ${error.message}`)
  return data?.[0] ?? null
}
