import { createClient } from '@supabase/supabase-js'
import { writeFileSync } from 'fs'
import { computeActivityGaps } from '../src/lib/activity-gap.js'
import { computeApplicantPoolPosition } from '../src/lib/corpus-stats.js'
import { analyzeProfile } from '../src/lib/gap-analyzer.js'
import { getProfile, listActivities } from '../src/lib/profiles.js'
import { loadSchoolStatsRows } from '../src/lib/school-comparison.js'

// Generates the static fixtures the browser bundle ships for Demo mode.
//
// Why static instead of live: pm_profiles/pm_activities are RLS-scoped to
// auth.uid() = user_id, so the browser (anon key) can never read another
// user's row — including the 4 archetype accounts, which belong to their
// own auth.users, not whoever is actually logged in. pm_school_stats has no
// RLS policy at all (session 1, still "pending source license review"), so
// the browser can't read it live even for the CURRENT user. Both need a
// service-role read at generation time; the output here is what the browser
// actually ships and reads at runtime — no live Supabase calls for Demo mode
// or the school comparison table in either mode.
//
// Re-run after any change to the 4 archetypes or to pm_school_stats' scraped data:
//   npm run export-demo-fixtures

const ARCHETYPE_USER_IDS: Record<string, string> = {
  grinder: '64620492-5eac-4111-86c2-210774b5f001',
  flipped: '3b92baf1-c5e1-47c6-a6aa-7bd110fb5a18',
  balanced: '430e8e4a-b0d4-4aae-bb38-5993289ff9c0',
  climber: '815b38d9-7539-4f97-80ce-40a71a3f6293',
}

const CYCLE_YEARS = [2023, 2025]

const OUT_DIR = 'premed/src/ui/data'

async function main() {
  const SUPABASE_URL = process.env.SUPABASE_URL
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local')
    process.exit(1)
  }
  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

  console.log('Loading pm_school_stats snapshot...')
  const schoolStats = await loadSchoolStatsRows(supabase)
  console.log(`  ${schoolStats.length} schools with both median_gpa and median_mcat.`)

  const archetypes = []
  for (const [key, userId] of Object.entries(ARCHETYPE_USER_IDS)) {
    console.log(`Building fixture for "${key}"...`)
    const profile = await getProfile(supabase, userId)
    if (!profile) throw new Error(`No pm_profiles row for archetype "${key}" (user_id=${userId}). Run seed-archetypes first.`)
    if (profile.gpa_cum === null || profile.mcat_total === null) {
      throw new Error(`Archetype "${key}" is missing gpa_cum/mcat_total — cannot build a fixture.`)
    }
    const slice = { gpa: profile.gpa_cum, mcat: profile.mcat_total }

    const activities = await listActivities(supabase, profile.id)
    const activityGaps = await computeActivityGaps(activities) // static baseline — see handoff for why
    const poolPositions = await Promise.all(CYCLE_YEARS.map(year => computeApplicantPoolPosition(supabase, slice, year)))
    const gapAnalysis = await analyzeProfile(supabase, slice, CYCLE_YEARS)

    archetypes.push({
      key,
      profile,
      activities,
      activityGaps,
      poolPositions,
      gapAnalysis,
    })
  }

  const archetypesOut = `// GENERATED by premed/pipeline/export-demo-fixtures.ts — do not hand-edit.
// Regenerate with: npm run export-demo-fixtures
import type { CategoryGap } from '../../lib/activity-gap.js'
import type { ApplicantPoolPosition } from '../../lib/corpus-stats.js'
import type { GapAnalysis } from '../../lib/gap-analyzer.js'
import type { PmActivity, PmProfile } from '../../lib/schemas.js'

export type DemoArchetypeFixture = {
  key: string
  profile: PmProfile
  activities: PmActivity[]
  activityGaps: CategoryGap[]
  poolPositions: ApplicantPoolPosition[]
  gapAnalysis: GapAnalysis
}

export const DEMO_ARCHETYPES: DemoArchetypeFixture[] = ${JSON.stringify(archetypes, null, 2)}
`
  writeFileSync(`${OUT_DIR}/demo-archetypes.generated.ts`, archetypesOut, 'utf-8')
  console.log(`Wrote ${OUT_DIR}/demo-archetypes.generated.ts`)

  const schoolStatsOut = `// GENERATED by premed/pipeline/export-demo-fixtures.ts — do not hand-edit.
// Regenerate with: npm run export-demo-fixtures
import type { SchoolStatsRow } from '../../lib/school-comparison.js'

export const SCHOOL_STATS_SNAPSHOT: SchoolStatsRow[] = ${JSON.stringify(schoolStats, null, 2)}
`
  writeFileSync(`${OUT_DIR}/school-stats-snapshot.generated.ts`, schoolStatsOut, 'utf-8')
  console.log(`Wrote ${OUT_DIR}/school-stats-snapshot.generated.ts`)
}

main().catch(err => {
  console.error(err instanceof Error ? err.message : err)
  process.exit(1)
})
